######################################################################
# Automatically generated by qmake (2.01a) Mon May 13 11:36:13 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . headers sources UI
INCLUDEPATH += .

# Input
HEADERS += headers/MainWindow.h
FORMS += UI/mainwindow.ui
SOURCES += main.cpp sources/MainWindow.cpp
RESOURCES += MainWindow.qrc
